Repository pknu-wap/Music_DNA, pull requests merged in 2024-05, with the labels that each got.

#17 재즈결과 로직수정
  music/src/Pages/Result/Jazz.js
Labels: 이찬이, FrontEnd

#20 진행률 수정
  music/src/Pages/FirstTest/FirstPage.js
  music/src/Pages/FirstTest/FirstPage1.js
  music/src/Pages/SecondTest/SecondPage.js
  music/src/Pages/SecondTest/SecondPage1.js
  music/src/Pages/SecondTest/SecondPage2.js
  music/src/Pages/SecondTest/SecondPage3.js
Labels: 서성원, FrontEnd, 테스트페이지

#23 재즈, 팝 문항 추가
  music/src/Pages/SecondTest/SecondPage4.js
  music/src/Pages/SecondTest/SecondPage5.js
  music/src/Pages/SecondTest/SecondPage9.js
  music/src/Router/Routers.js
Labels: 서성원, FrontEnd, 테스트페이지

#24 main화면 반응형
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#25 힙합,락,알앤비 문항 추가
  music/src/Pages/SecondTest/SecondPage6.js
  music/src/Pages/SecondTest/SecondPage7.js
  music/src/Pages/SecondTest/SecondPage8.js
  music/src/Router/Routers.js
Labels: 서성원, FrontEnd, 테스트페이지

#26 백엔드 연동 코드 추가
  music/src/Pages/SecondTest/SecondPage9.js
Labels: 서성원, FrontEnd

#28 Rockbox를 RbBox로 변경
  music/src/Pages/SecondTest/SecondPage8.js
Labels: 서성원, FrontEnd, 테스트페이지

#29 음악동시재생 방지
  music/src/Pages/FirstTest/FirstPage.js
  music/src/Pages/FirstTest/FirstPage1.js
Labels: 서성원, FrontEnd, 테스트페이지

#30 진행바 변경
  music/package.json
  music/src/Components/testData.js
  music/src/Pages/FirstTest/FirstPage.js
  music/src/Pages/FirstTest/FirstPage1.js
  music/src/Pages/SecondTest/SecondPage.js
  music/src/Pages/SecondTest/SecondPage1.js
  music/src/Pages/SecondTest/SecondPage2.js
  music/src/Pages/SecondTest/SecondPage3.js
  music/src/Pages/SecondTest/SecondPage4.js
  music/src/Pages/SecondTest/SecondPage5.js
  music/src/Pages/SecondTest/SecondPage6.js
  music/src/Pages/SecondTest/SecondPage7.js
  music/src/Pages/SecondTest/SecondPage8.js
  music/src/Pages/SecondTest/SecondPage9.js
Labels: 서성원, FrontEnd, 테스트페이지

#31 R&B 결과 페이지 디자인 적용
  music/public/test.png
  music/src/Pages/Result/Rb.js
  music/src/Pages/Result/Result.css
Labels: 이찬이, FrontEnd, 결과페이지

#32 링크버튼 및 진행바 컴포넌트로 설정
  music/src/Components/NextButton.css
  music/src/Components/NextButton.js
  music/src/Components/useCompleted.js
  music/src/Pages/FirstTest/FirstPage.css
  music/src/Pages/FirstTest/FirstPage.js
  music/src/Pages/FirstTest/FirstPage1.js
  music/src/Pages/SecondTest/SecondPage.js
  music/src/Pages/SecondTest/SecondPage1.js
  music/src/Pages/SecondTest/SecondPage2.js
  music/src/Pages/SecondTest/SecondPage3.js
  music/src/Pages/SecondTest/SecondPage4.js
  music/src/Pages/SecondTest/SecondPage5.js
  music/src/Pages/SecondTest/SecondPage6.js
  music/src/Pages/SecondTest/SecondPage7.js
  music/src/Pages/SecondTest/SecondPage8.js
  music/src/Pages/SecondTest/SecondPage9.js
Labels: 서성원, FrontEnd, 테스트페이지

#33 음원 요청 코드
  music/src/Pages/FirstTest/FirstPage.js
  music/src/Pages/FirstTest/FirstPage1.js
Labels: 서성원, FrontEnd, 테스트페이지

#34 결과 R&B
  music/public/19.png
  music/src/Pages/Result/Rb.js
  music/src/Pages/Result/Result.css
Labels: 이찬이, FrontEnd, 결과페이지

#35 jazz 결과내용
  music/src/Pages/Result/Jazz.js
Labels: 이찬이, FrontEnd, 결과페이지

#36 텍스트 1차 변경
  music/src/Pages/SecondTest/SecondPage.js
  music/src/Pages/SecondTest/SecondPage1.js
  music/src/Pages/SecondTest/SecondPage2.js
  music/src/Pages/SecondTest/SecondPage3.js
  music/src/Pages/SecondTest/SecondPage5.js
  music/src/Pages/SecondTest/SecondPage6.js
  music/src/Pages/SecondTest/SecondPage7.js
  music/src/Pages/SecondTest/SecondPage8.js
  music/src/Pages/SecondTest/SecondPage9.js
Labels: 서성원, FrontEnd, 테스트페이지

#37 hiphop결과내용
  music/src/Pages/Result/Hip.js
  music/src/Pages/Result/Result.css
  music/src/Router/Routers.js
Labels: 이찬이, FrontEnd, 결과페이지

#38 pop결과 내용
  music/public/pop_m1.jpg
  music/public/pop_m2.jpg
  music/public/pop_m3.jpg
  music/public/pop_m4.jpg
  music/public/pop_m5.webp
  music/public/pop_singer1.png
  music/public/pop_singer2.png
  music/public/pop_singer3.png
  music/public/pop_singer4.png
  music/public/pop_singer5.png
  music/src/Pages/Result/Pop.js
  music/src/Pages/Result/Result.css
Labels: 이찬이, FrontEnd, 결과페이지

#39 rock 결과 내용
  music/public/rock_m1.jpg
  music/public/rock_m2.webp
  music/public/rock_m3.webp
  music/public/rock_m4.jpg
  music/public/rock_m5.jpg
  music/public/rock_singer1.png
  music/public/rock_singer2.png
  music/public/rock_singer3.png
  music/public/rock_singer4.png
  music/public/rock_singer5.png
  music/src/Pages/Result/Rock.js
Labels: 이찬이, FrontEnd, 결과페이지

#40 Rock,Pop 결과 진행바 수정
  music/src/Pages/Result/Hip.js
  music/src/Pages/Result/Pop.js
  music/src/Pages/Result/Rock.js
Labels: 서성원, FrontEnd, 결과페이지

#41 R&b,Hip,Jazz 내용 수정
  music/public/hip_m1.jpg
  music/public/hip_m2.jpg
  music/public/hip_m3.jpg
  music/public/hip_m4.webp
  music/public/hip_m5.webp
  music/public/hip_singer1.png
  music/public/hip_singer2.png
  music/public/hip_singer3.png
  music/public/hip_singer4.png
  music/public/hip_singer5.png
  music/public/jazz_m1.jpg
  music/public/jazz_m2.jpg
  music/public/jazz_m3.jpg
  music/public/jazz_m4.jpg
  music/public/jazz_m5.jpg
  music/public/jazz_singer1.png
  music/public/jazz_singer2.png
  music/public/jazz_singer3.png
  music/public/jazz_singer4.png
  music/public/jazz_singer5.png
  music/public/rb_m1.jpg
  music/public/rb_m2.jpg
  music/public/rb_m3.jpg
  music/public/rb_m4.jpg
  music/public/rb_m5.jpg
  music/public/rb_singer1.png
  music/public/rb_singer2.png
  music/public/rb_singer3.png
  music/public/rb_singer4.png
  music/public/rb_singer5.png
  music/src/Pages/Result/Hip.js
  music/src/Pages/Result/Jazz.js
  music/src/Pages/Result/Rb.js
  music/src/Pages/Result/Result.css
Labels: 이찬이, FrontEnd, 결과페이지

#42 Hip,Jazz,Rb 진행바 변경
  music/src/Pages/Result/Hip.js
  music/src/Pages/Result/Jazz.js
  music/src/Pages/Result/Rb.js
Labels: 서성원, FrontEnd, 결과페이지

#43 결과페이지 진행바 사이즈 조절
  music/src/Pages/Result/Hip.js
  music/src/Pages/Result/Jazz.js
  music/src/Pages/Result/Pop.js
  music/src/Pages/Result/Rb.js
  music/src/Pages/Result/Result.css
  music/src/Pages/Result/Rock.js
Labels: 서성원, FrontEnd, 결과페이지

#44 test
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#45 test2
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#46 ipadAir가로
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#47 update iPad
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#48 iPadAir
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#49 iPad update
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#51 ipadAir_반응형 test2
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#52 팝 모달 틀만 구현
  music/package.json
  music/src/Pages/Result/Modal.js
  music/src/Pages/Result/ModalCon.js
  music/src/Pages/Result/Pop.js
Labels: 서성원, FrontEnd, 결과페이지

#53 재즈 모달 추가
  music/src/Pages/Result/Jazz.js
  music/src/Pages/Result/ModalCon.js
  music/src/Pages/Result/Pop.js
Labels: 서성원, FrontEnd, 결과페이지

#54 힙합 모달 추가
  music/src/Pages/Result/Hip.js
  music/src/Pages/Result/ModalCon.js
Labels: 서성원, FrontEnd, 결과페이지

#55 mobile반응형
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#56 mobile 반응형 수정1
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#57 락 모달 추가
  music/src/Pages/Result/ModalCon.js
  music/src/Pages/Result/Rock.js
Labels: 서성원, FrontEnd, 결과페이지

#58 알앤비 모달추가
  music/src/Pages/Result/ModalCon.js
  music/src/Pages/Result/Rb.js
Labels: 서성원, FrontEnd, 결과페이지

#59 mobile반응형_버튼, 설명 수정
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#60 mobile반응형-타이틀, 버튼, 설명 위치 조정
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#61 반응형mobile_ 타이틀, 버튼 , 설명 위치조정2
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#62 반응형 mobile- 버튼 조정
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#63 mobile 반응형 수정_타이틀, 버튼, 텍스트 위치 수정
  music/src/App.css
  music/src/Pages/Main/Main.js
Labels: 이찬이, FrontEnd, 메인페이지

#65 mobile반응형_ 텍스트 위치 수정
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#66 mobile반응형_텍스트 위치 수정
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#67 FirstTest disabled 기능추가
  music/src/Components/NextButton.js
  music/src/Pages/FirstTest/FirstPage.js
  music/src/Pages/FirstTest/FirstPage1.js
Labels: 서성원, FrontEnd, 테스트페이지

#68 ipad_Air 반응형_ firstpage 기초 작업
  music/src/Components/CheckBox.style.js
  music/src/Components/NextButton.css
  music/src/Pages/FirstTest/FirstPage.css
Labels: 이찬이, FrontEnd, 테스트페이지

#70 결과 모달창 디자인 수정
  music/src/Pages/Result/Modal.js
Labels: 서성원, FrontEnd, 결과페이지
