Repository pknu-wap/Music_DNA, pull requests merged in 2024-06, with the labels that each got.

#71 모달 하위장르 타이틀 변경
  music/src/Pages/Result/Hip.js
  music/src/Pages/Result/Jazz.js
  music/src/Pages/Result/ModalCon.js
  music/src/Pages/Result/Pop.js
  music/src/Pages/Result/Rb.js
  music/src/Pages/Result/Rock.js
Labels: 서성원, FrontEnd, 결과페이지

#73 결과페이지 장르 타이틀 변경
  music/src/Pages/Result/Hip.js
  music/src/Pages/Result/Jazz.js
  music/src/Pages/Result/Pop.js
  music/src/Pages/Result/Rb.js
  music/src/Pages/Result/Rock.js
Labels: 서성원, FrontEnd, 결과페이지

#74 분포도와 플레이리스트 위치 변경
  music/src/Pages/Result/Hip.js
  music/src/Pages/Result/Jazz.js
  music/src/Pages/Result/Pop.js
  music/src/Pages/Result/Rb.js
  music/src/Pages/Result/Rock.js
Labels: 서성원, FrontEnd, 결과페이지

#76 결과페이지 음악버튼에 url설정
  music/src/Pages/Result/Hip.js
  music/src/Pages/Result/Jazz.js
  music/src/Pages/Result/Pop.js
  music/src/Pages/Result/Rb.js
  music/src/Pages/Result/Rock.js
Labels: 서성원, FrontEnd, 결과페이지

#77 Mobile_반응형_firstpage 개체 위치 수정
  music/src/Components/NextButton.css
  music/src/Pages/FirstTest/FirstPage.css
Labels: 이찬이, FrontEnd, 테스트페이지

#78 배경색 변경
  music/public/play.png
  music/src/Pages/Result/Result.css
Labels: 서성원, FrontEnd, 결과페이지

#79 Mobile_반응형_firstpage 위치 수정
  music/src/Pages/FirstTest/FirstPage.css
Labels: 이찬이, FrontEnd, 테스트페이지

#80 Mobile_반응형_firstpage 버튼 위치 수정
  music/src/Components/NextButton.css
Labels: 이찬이, FrontEnd, 테스트페이지

#81 Mobile_반응형_secondpage 기초 작업
  music/src/Pages/SecondTest/SecondPage.css
Labels: 이찬이, FrontEnd, 테스트페이지

#82 Mobile_반응형_secondpage_텍스트 박스 위치 수
  music/src/Pages/SecondTest/SecondPage.css
Labels: 이찬이, FrontEnd, 테스트페이지

#83 Mobile_반응형_secondpage_텍스트 박스 높이 수정(4)
  music/src/Pages/SecondTest/SecondPage.css
Labels: 이찬이, FrontEnd, 테스트페이지

#84 Mobile_반응형_secondpage_텍스트 박스 높이 수정
  music/src/Pages/SecondTest/SecondPage.css
Labels: 이찬이, FrontEnd, 테스트페이지

#85 Mobile_반응형_resultpage_기초 작업
  music/src/Pages/Result/Result.css
Labels: 이찬이, FrontEnd, 결과페이지

#86 Mobile_반응형_main,secondpage 수정
  music/src/App.css
  music/src/Pages/FirstTest/FirstPage.css
  music/src/Pages/SecondTest/SecondPage.css
Labels: 이찬이, FrontEnd, 테스트페이지, 메인페이지

#87 Mobile_반응형_오류 수정
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#88 Mobile_반응형_Firstpage 오류 수정
  music/src/Pages/FirstTest/FirstPage.css
Labels: 이찬이, FrontEnd, 테스트페이지

#89 Mobile_반응형_Firstpage 버튼
  music/src/Components/NextButton.css
  music/src/Pages/FirstTest/FirstPage.css
Labels: 이찬이, FrontEnd, 테스트페이지

#90 Mobile_반응형_Firstpage 버튼, 텍스트 박스
  music/src/Components/NextButton.css
  music/src/Pages/FirstTest/FirstPage.css
Labels: 이찬이, FrontEnd, 테스트페이지

#91 Mobile_반응형_secondpage 배경화면 길이 조절
  music/src/Pages/SecondTest/SecondPage.css
Labels: 이찬이, FrontEnd, 테스트페이지

#92 뮤직아이콘 마우스 pointer
  music/src/Pages/Result/Hip.js
  music/src/Pages/Result/Jazz.js
  music/src/Pages/Result/Pop.js
  music/src/Pages/Result/Rb.js
  music/src/Pages/Result/Rock.js
Labels: 서성원, FrontEnd, 결과페이지

#93 팝 모달 제목 바꿈
  music/src/Pages/Result/Pop.js
Labels: 서성원, FrontEnd, 결과페이지

#94 Mobile_반응형_resultpage 수정
  music/src/Pages/Result/Result.css
Labels: 이찬이, FrontEnd, 결과페이지

#95 모달,진행바 위치 수정
  music/src/Pages/Result/Hip.js
  music/src/Pages/Result/Jazz.js
  music/src/Pages/Result/Pop.js
  music/src/Pages/Result/Rb.js
  music/src/Pages/Result/Rock.js
Labels: 서성원, FrontEnd, 결과페이지

#96 모달버튼 패딩조절
  music/src/Pages/Result/Hip.js
  music/src/Pages/Result/Jazz.js
  music/src/Pages/Result/Pop.js
  music/src/Pages/Result/Rb.js
  music/src/Pages/Result/Rock.js
Labels: 서성원, FrontEnd, 결과페이지

#97 진행바 디자인 수정, 이미지 커서 포인터
  music/src/Pages/Result/Hip.js
  music/src/Pages/Result/Jazz.js
  music/src/Pages/Result/Pop.js
  music/src/Pages/Result/Rb.js
  music/src/Pages/Result/Result.css
  music/src/Pages/Result/Rock.js
Labels: 서성원, FrontEnd, 결과페이지

#98 모달창 대표아티스트 추가
  music/src/Pages/Result/ModalCon.js
Labels: 서성원, FrontEnd, 결과페이지

#99 checkbox 색상 및 크기 수정
  music/src/Components/CheckBox.style.js
Labels: 이찬이, FrontEnd, 테스트페이지

#100 Mobile_반응형_Main 배경화면 조정
  music/src/App.css
Labels: 이찬이, FrontEnd, 메인페이지

#101 다음으로 넘어가기 방지
  music/src/Components/NextButton.js
  music/src/Pages/FirstTest/FirstPage.js
  music/src/Pages/FirstTest/FirstPage1.js
  music/src/Pages/SecondTest/Button/SecondBtn.css
  music/src/Pages/SecondTest/Button/SecondBtn.js
  music/src/Pages/SecondTest/SecondPage.js
  music/src/Pages/SecondTest/SecondPage1.js
  music/src/Pages/SecondTest/SecondPage2.js
  music/src/Pages/SecondTest/SecondPage3.js
  music/src/Pages/SecondTest/SecondPage4.js
  music/src/Pages/SecondTest/SecondPage5.js
  music/src/Pages/SecondTest/SecondPage6.js
  music/src/Pages/SecondTest/SecondPage7.js
  music/src/Pages/SecondTest/SecondPage8.js
  music/src/Pages/SecondTest/SecondPage9.js
Labels: 서성원, FrontEnd, 테스트페이지

#102 SecondPage 다음으로 버튼 수정
  music/src/Pages/FirstTest/FirstPage.css
  music/src/Pages/FirstTest/FirstPage.js
  music/src/Pages/FirstTest/FirstPage1.js
  music/src/Pages/SecondTest/Button/SecondBtn.css
  music/src/Pages/SecondTest/Button/SecondBtn.js
  music/src/Pages/SecondTest/SecondPage.js
  music/src/Pages/SecondTest/SecondPage4.js
Labels: 서성원, FrontEnd, 테스트페이지

#103 모달창, 진행바 모바일 반응형
  music/src/Pages/Result/Hip.js
  music/src/Pages/Result/Jazz.js
  music/src/Pages/Result/Pop.js
  music/src/Pages/Result/Rb.js
  music/src/Pages/Result/Result.css
  music/src/Pages/Result/Rock.js
Labels: 서성원, FrontEnd, 결과페이지

#104 Mobile_반응형_버튼, 텍스트 박스, 체크박스 조정
  music/src/Components/CheckBox.style.js
  music/src/Pages/FirstTest/FirstPage.css
  music/src/Pages/SecondTest/Button/SecondBtn.css
Labels: 이찬이, FrontEnd, 테스트페이지

#105 Mobile_음악 버튼, 결과 페이지 조정
  music/src/Pages/FirstTest/FirstPage.css
  music/src/Pages/Result/Result.css
Labels: 이찬이, FrontEnd, 테스트페이지, 결과페이지

#106 Feature/font
  music/src/App.css
  music/src/Pages/FirstTest/FirstPage.css
  music/src/Pages/Result/Result.css
  music/src/Pages/SecondTest/SecondPage.css
Labels: 이찬이, FrontEnd, 테스트페이지, 결과페이지, 메인페이지

#108 대표아티스트 수정
  music/src/Pages/Result/ModalCon.js
Labels: 서성원, FrontEnd, 결과페이지

#109 장르수정
  music/src/Pages/Result/ModalCon.js
  music/src/Pages/Result/Pop.js
  music/src/Pages/Result/Rock.js
  music/src/Pages/SecondTest/SecondPage.js
  music/src/Pages/SecondTest/SecondPage3.js
  music/src/Pages/SecondTest/SecondPage4.js
  music/src/Pages/SecondTest/SecondPage7.js
Labels: 서성원, FrontEnd, 테스트페이지, 결과페이지

#111 아티스트 수정
  music/public/pop_m5.png
  music/public/pop_m5.webp
  music/public/pop_singer5.png
  music/public/rb_m3.jpeg
  music/public/rb_m3.jpg
  music/public/rock_m2.webp
  music/public/rock_singer2.png
  music/src/Pages/Result/ModalCon.js
  music/src/Pages/Result/Pop.js
  music/src/Pages/Result/Rb.js
  music/src/Pages/Result/Rock.js
Labels: 서성원, FrontEnd, 결과페이지
